<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BouncyCastle.Crypto">
      <HintPath>SDK\BouncyCastle.Crypto.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="Zatca.EInvoice.SDK">
      <HintPath>SDK\Zatca.EInvoice.SDK.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="Zatca.EInvoice.SDK.Contracts">
      <HintPath>SDK\Zatca.EInvoice.SDK.Contracts.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="Zatca.EInvoice.SDK.Saxon">
      <HintPath>SDK\Zatca.EInvoice.SDK.Saxon.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>

    <Content Include="ikvm\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>

    <Content Include="runtimes\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
